# Generated by Django 2.2.4 on 2019-08-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowl',
            name='style',
            field=models.CharField(default='Classic', max_length=50),
        ),
    ]
