# Generated by Django 2.2.4 on 2019-08-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0002_auto_20190823_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowl',
            name='ratings_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowl',
            name='ratings_sum',
            field=models.IntegerField(default=0),
        ),
    ]
